# Generated by Django 4.2.6 on 2023-10-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isolated_backend', '0003_rename_user_comment_reply_reply_commentted_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_commentted_text',
            new_name='user_comment',
        ),
    ]
