# Generated by Django 4.2.6 on 2023-10-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isolated_backend', '0004_rename_reply_commentted_text_reply_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='user_comment',
            new_name='reply_commentted_text',
        ),
    ]
